// import React from 'react'

// const member = () => {
//   return (
//     <div>member</div>
//   )
// }

// export default member
import { column,UpCommingAdveture } from "./column"
import { DataTable } from "@/components/shared/admin/Table resources/data-table"

async function getData(): Promise<UpCommingAdveture[]> {
  // Fetch data from your API here.
 return[
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
  {
    id:1,
    trekName: "kashmir",
  startDate: "13-03-23",
  totalSeats: 32,
  bookedSeats: 34,
  booking: "Booking",
  Actions: "string",
  },
 ]
}

export default async function member() {
  const data = await getData()

  return (
    <div className="container mx-auto pb-4 bg-white">
      <div className="flex justify-between py-4 border-b-slate-200 border-b-[1px]">
        <p>Upcoming Adventure</p>
        <p>filter</p>
      </div>
      <div className="flex justify-end py-4 border-b-slate-200 border-b-[1px]">
        <p>search</p>
      </div>
      <DataTable columns={column} data={data} />
    </div>
  )
}


